modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "www.emptydust.com"
authors = "${mod_authors}"
description = '''${mod_description}'''

# 正确的依赖项声明方式
[[dependencies]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# 声明 okhttp3 依赖（如果需要）
[[dependencies]]
modId = "okhttp3"
mandatory = false # 模组是否可以没有 okhttp3 运行？
versionRange = "[4.12.0,)" # 根据你使用的 okhttp3 版本修改
ordering = "AFTER" # 确保在你的模组之后加载 okhttp3
side = "SERVER"